
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/bin/"
      - "/opt/homebrew/opt/libpq/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/paulo/Library/Application Support/reflex/bun/bin/"
      - "/Users/paulo/.antigravity/antigravity/bin/"
      - "/opt/homebrew/opt/mysql-client/bin/"
      - "/Users/paulo/.fly/bin/"
      - "/Users/paulo/Developer/workspaces/cpp/axmol/tools/cmdline/"
      - "/opt/homebrew/opt/python@3.12/libexec/bin/"
      - "/Users/paulo/.local/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/paulo/.dotnet/tools/"
      - "/Applications/Icons.app/Contents/MacOS/"
      - "/usr/local/opt/mysql-client/bin/"
      - "/Users/paulo/Library/Python/3.9/bin/"
      - "/Users/paulo/.gems/bin/"
      - "/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin/"
      - "/Users/paulo/Developer/workspaces/go/bin/"
      - "/Users/paulo/Developer/flutter/bin/"
      - "/Users/paulo/Library/Android/sdk/tools/bin/"
      - "/Users/paulo/Dropbox/Docs/Scripts/"
      - "/Users/paulo/Library/Mobile Documents/com~apple~CloudDocs/Documents/Scripts/"
      - "/opt/homebrew/Caskroom/android-ndk/28b/AndroidNDK13356709.app/Contents/NDK/"
      - "/Users/paulo/Library/Android/sdk/platform-tools/"
      - "/Users/paulo/.pub-cache/bin/"
      - "/Users/paulo/.cargo/bin/"
      - "/Users/paulo/.lmstudio/bin/"
    searched_directories:
      - "/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/bin/uname"
      - "/opt/homebrew/opt/libpq/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Users/paulo/Library/Application Support/reflex/bun/bin/uname"
      - "/Users/paulo/.antigravity/antigravity/bin/uname"
      - "/opt/homebrew/opt/mysql-client/bin/uname"
      - "/Users/paulo/.fly/bin/uname"
      - "/Users/paulo/Developer/workspaces/cpp/axmol/tools/cmdline/uname"
      - "/opt/homebrew/opt/python@3.12/libexec/bin/uname"
      - "/Users/paulo/.local/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/bin"
        - "/opt/homebrew/opt/libpq/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/paulo/Library/Application Support/reflex/bun/bin"
        - "~/.antigravity/antigravity/bin"
        - "/opt/homebrew/opt/mysql-client/bin"
        - "/Users/paulo/.fly/bin"
        - "/Users/paulo/Developer/workspaces/cpp/axmol/tools/cmdline"
        - "/opt/homebrew/opt/python@3.12/libexec/bin"
        - "/Users/paulo/.local/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Applications/Icons.app/Contents/MacOS"
        - "/opt/homebrew/opt/libpq/bin"
        - "/usr/local/opt/mysql-client/bin"
        - "/Users/paulo/Library/Python/3.9/bin"
        - "/Users/paulo/.gems/bin"
        - "/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin"
        - "/Users/paulo/Developer/workspaces/go/bin/"
        - "/Users/paulo/Developer/flutter/bin"
        - "/Users/paulo/Library/Android/sdk/tools/bin"
        - "/Users/paulo/Dropbox/Docs/Scripts/"
        - "/Users/paulo/Library/Mobile Documents/com~apple~CloudDocs/Documents/Scripts/"
        - "/opt/homebrew/Caskroom/android-ndk/28b/AndroidNDK13356709.app/Contents/NDK"
        - "/Users/paulo/Library/Android/sdk//platform-tools"
        - "/Users/paulo/.pub-cache/bin"
        - "/Users/paulo/.cargo/bin"
        - "/Users/paulo/.lmstudio/bin"
        - "/Users/paulo/.lmstudio/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/bin/"
      - "/opt/homebrew/opt/libpq/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/paulo/Library/Application Support/reflex/bun/bin/"
      - "/Users/paulo/.antigravity/antigravity/bin/"
      - "/opt/homebrew/opt/mysql-client/bin/"
      - "/Users/paulo/.fly/bin/"
      - "/Users/paulo/Developer/workspaces/cpp/axmol/tools/cmdline/"
      - "/opt/homebrew/opt/python@3.12/libexec/bin/"
      - "/Users/paulo/.local/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/paulo/.dotnet/tools/"
      - "/Applications/Icons.app/Contents/MacOS/"
      - "/usr/local/opt/mysql-client/bin/"
      - "/Users/paulo/Library/Python/3.9/bin/"
      - "/Users/paulo/.gems/bin/"
      - "/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin/"
      - "/Users/paulo/Developer/workspaces/go/bin/"
      - "/Users/paulo/Developer/flutter/bin/"
      - "/Users/paulo/Library/Android/sdk/tools/bin/"
      - "/Users/paulo/Dropbox/Docs/Scripts/"
      - "/Users/paulo/Library/Mobile Documents/com~apple~CloudDocs/Documents/Scripts/"
      - "/opt/homebrew/Caskroom/android-ndk/28b/AndroidNDK13356709.app/Contents/NDK/"
      - "/Users/paulo/Library/Android/sdk/platform-tools/"
      - "/Users/paulo/.pub-cache/bin/"
      - "/Users/paulo/.cargo/bin/"
      - "/Users/paulo/.lmstudio/bin/"
    searched_directories:
      - "/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/bin/install_name_tool"
      - "/opt/homebrew/opt/libpq/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/Users/paulo/Library/Application Support/reflex/bun/bin/install_name_tool"
      - "/Users/paulo/.antigravity/antigravity/bin/install_name_tool"
      - "/opt/homebrew/opt/mysql-client/bin/install_name_tool"
      - "/Users/paulo/.fly/bin/install_name_tool"
      - "/Users/paulo/Developer/workspaces/cpp/axmol/tools/cmdline/install_name_tool"
      - "/opt/homebrew/opt/python@3.12/libexec/bin/install_name_tool"
      - "/Users/paulo/.local/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/bin"
        - "/opt/homebrew/opt/libpq/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/paulo/Library/Application Support/reflex/bun/bin"
        - "~/.antigravity/antigravity/bin"
        - "/opt/homebrew/opt/mysql-client/bin"
        - "/Users/paulo/.fly/bin"
        - "/Users/paulo/Developer/workspaces/cpp/axmol/tools/cmdline"
        - "/opt/homebrew/opt/python@3.12/libexec/bin"
        - "/Users/paulo/.local/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Applications/Icons.app/Contents/MacOS"
        - "/opt/homebrew/opt/libpq/bin"
        - "/usr/local/opt/mysql-client/bin"
        - "/Users/paulo/Library/Python/3.9/bin"
        - "/Users/paulo/.gems/bin"
        - "/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin"
        - "/Users/paulo/Developer/workspaces/go/bin/"
        - "/Users/paulo/Developer/flutter/bin"
        - "/Users/paulo/Library/Android/sdk/tools/bin"
        - "/Users/paulo/Dropbox/Docs/Scripts/"
        - "/Users/paulo/Library/Mobile Documents/com~apple~CloudDocs/Documents/Scripts/"
        - "/opt/homebrew/Caskroom/android-ndk/28b/AndroidNDK13356709.app/Contents/NDK"
        - "/Users/paulo/Library/Android/sdk//platform-tools"
        - "/Users/paulo/.pub-cache/bin"
        - "/Users/paulo/.cargo/bin"
        - "/Users/paulo/.lmstudio/bin"
        - "/Users/paulo/.lmstudio/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
